### ISSUE TITLE
async keyword doesn't work with arrow syntax

### ISSUE THREAD

**Issue by parenthetical** [HerringtonDarkholme/typescript-repl#8] opened 2016-05-06 13:52 UTC
This works:

```
> let f = async function() { return "foo"; }
> f()
Promise { 'foo' }
```

But this doesn't:

```
> let ff = async () => "foo";
evalmachine.<anonymous>:1
var ff = function () __awaiter(this, void 0, void 0, function* () { return "foo"; });
                     ^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInContext (vm.js:43:16)
    at startEvaluate (/usr/lib/node_modules/tsun/bin/src/repl.js:409:25)
    at replLoop (/usr/lib/node_modules/tsun/bin/src/repl.js:438:9)
    at /usr/lib/node_modules/tsun/bin/src/repl.js:513:9
    at Interface._onLine (readline.js:217:5)
    at Interface._line (readline.js:561:8)
    at Interface._ttyWrite (readline.js:838:14)
    at ReadStream.onkeypress (readline.js:114:10)
    at emitTwo (events.js:106:13)
    at ReadStream.emit (events.js:191:7)
```

**Comment by HerringtonDarkholme** [comment] 2016-05-06 14:45
Thanks for reporting!

This is a known issue because tsun compiles TS down to ES5, and `async` is not officially supported on ES5.

Once the configuration feature is supported you can change the compile target to ES6 and use node6 to execute tsun.
For now I think the only way to achieve this is to change the tsun source code in your node_modules :(

**Comment by monkar** [comment] 2016-06-10 00:18
on run "tsun":

$ tsun
TSUN : TypeScript Upgraded Node
type in TypeScript expression to evaluate
type :help for commands in repl

> readline.js:616
>   var strBeforeCursor = this._prompt + this.line.substring(0, this.cursor);
>                                                 ^

TypeError: Cannot read property 'substring' of undefined
    at Interface._getCursorPos (readline.js:616:49)
    at afterSuggestion (C:\Users\Edgar\AppData\Roaming\npm\node_modules\tsun\node_modules\node-color-readline\index.js:75:26)
    at renderCurrentLine (C:\Users\Edgar\AppData\Roaming\npm\node_modules\tsun\node_modules\node-color-readline\index.js:71:5)
    at Interface._writeToOutput (C:\Users\Edgar\AppData\Roaming\npm\node_modules\tsun\node_modules\node-color-readline\index.js:42:5)
    at Interface.prompt (readline.js:185:10)
    at Interface.question (readline.js:198:12)
    at repl (C:\Users\Edgar\AppData\Roaming\npm\node_modules\tsun\bin\src\repl.js:472:8)
    at Object.startRepl (C:\Users\Edgar\AppData\Roaming\npm\node_modules\tsun\bin\src\repl.js:517:5)
    at Object.<anonymous> (C:\Users\Edgar\AppData\Roaming\npm\node_modules\tsun\bin\tsun.js:31:8)
    at Module._compile (module.js:409:26)

**Comment by HerringtonDarkholme** [comment] 2016-06-10 03:10
@monkar Can you open a new issue for this?
And, I cannot reproduce this. Maybe this is a windows problem I guess.

**Comment by HerringtonDarkholme** [comment] 2016-06-10 06:07
Closed via https://github.com/HerringtonDarkholme/typescript-repl/commit/2e3eeb0a52136e66a394e0a774183d4f0ffc537a

**Closed as completed by HerringtonDarkholme** 2016-06-10 06:07 UTC
Labels: enhancement

**Comment by HerringtonDarkholme** [comment] 2016-06-10 06:08
@parenthetical Now tsun will read your `tsconfig.json`!

You can change target to `ES6` and execute tsun under node6+. async arrow syntax should work under that configuration.
