### ISSUE TITLE
Erratic behavior across :clear command

### ISSUE THREAD

**Issue by niwsa** [HerringtonDarkholme/typescript-repl#10] opened 2016-07-15 17:44 UTC
In the below snippet I am not able to re use the same variable across tsun :clear command

```
> let a = 2
undefined
> a
2
> :clear
> let a = 2
undefined
> a
evalmachine.<anonymous>:1
a;
^
ReferenceError: a is not defined
    at evalmachine.<anonymous>:1:1
    at Object.exports.runInContext (vm.js:44:17)
    at startEvaluate (/usr/local/lib/node_modules/tsun/bin/src/repl.js:199:25)
    at replLoop (/usr/local/lib/node_modules/tsun/bin/src/repl.js:223:9)
    at /usr/local/lib/node_modules/tsun/bin/src/repl.js:330:9
    at Interface._onLine (readline.js:222:5)
    at Interface._line (readline.js:566:8)
    at Interface._ttyWrite (readline.js:843:14)
    at ReadStream.onkeypress (readline.js:115:10)
    at emitTwo (events.js:106:13)
> 
```

**Comment by HerringtonDarkholme** [comment] 2016-07-16 09:07
Thanks for reporting.
I'm digging into it.

**Comment by HerringtonDarkholme** [comment] 2016-07-16 09:15
Fixed in https://github.com/HerringtonDarkholme/typescript-repl/commit/035aab6675fa67deb08b6afcf7042f328b8ed191

**Closed as completed by HerringtonDarkholme** 2016-07-16 09:15 UTC
Labels: bug

**Comment by niwsa** [comment] 2016-07-16 12:20
@HerringtonDarkholme :+1: The other bug being more general in the sense that "its a typescript bug"?

**Comment by HerringtonDarkholme** [comment] 2016-07-16 12:23
No, it is an implementation bug.

tsun uses a lot of dirty tricks to mock typescript's repl because typescript's code emission is not a faithful translation of input code. So this is a bug caused by my neglect.

**Comment by niwsa** [comment] 2016-07-16 12:26
I have another query as to which is the targeted JS here (ES3 or ES5 or ES2015).For tsc you have the option`-t VERSION, --target VERSION        Specify ECMAScript target version: 'ES3' (default), 'ES5', or 'ES2015' (experimental)`?

**Comment by HerringtonDarkholme** [comment] 2016-07-16 12:29
The default target is es5. You can change the target via tsconfig.json in the same directory you execute tsun.

**Comment by niwsa** [comment] 2016-07-16 12:29
Cool !! Saw it in the readme :)
